# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for ATA over Ethernet
#

CONTEXT_ANALYSIS := y

obj-$(CONFIG_ATA_OVER_ETH)	+= aoe.o
aoe-y := aoeblk.o aoechr.o aoecmd.o aoedev.o aoemain.o aoenet.o
